version: '3.8'
services:
  myapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "test"
      SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/plus_project"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATA_REDIS_HOST: "localhost"
      SPRING_DATA_REDIS_PORT: "6379"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JAVA_OPTS: "-Xms128m -Xmx256m"
    restart: on-failure
