version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plus_project
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  myapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "test"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/plus_project"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-1234}
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-A3F27E88C1D0B54E9A11FF67A18C3D92A451B5E69D2E0E31F2A38DBA1B47F6D1}
      JAVA_OPTS: "-Xms128m -Xmx256m"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
