version: '3.8'
services:
  myapp:
    image: 600627346244.dkr.ecr.ap-northeast-2.amazonaws.com/plus-project:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/plus_project"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_DATA_REDIS_PORT: "6379"
      JWT_SECRET_KEY: "A3F27E88C1D0B54E9A11FF67A18C3D92A451B5E69D2E0E31F2A38DBA1B47F6D1"
      JAVA_OPTS: "-Xms128m -Xmx256m"
    deploy:
      resources:
        limits:
          memory: 512m
  db:
    image: mysql:8.0
    container_name: plus-project-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: plus_project
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234 && sleep 5" ]
      interval: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256m
  redis:
    image: redis:6.0
    container_name: plus-project-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 128m