name: CI/CD Test
on:
  push:
    branches:
      - jeonjiho/ci-cd
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test